### ISSUE TITLE
Fatal: A mongoDB is required

### ISSUE THREAD

**Issue by 3sv1n** [StrapBot/StrapBot#3]
even after i create a cluster in mongodb atlas and add the environment url to mongo.py, it always gives error saying, 
```
    raise RuntimeError
RuntimeError
Fatal	A MongoDB is required.
```

pls help me on ho to fix...

**Comment by Fleny113** [comment]
I think you need to put `MONGODB` into the .env file, not changing the string into the .py file

**Comment by devjoshua312** [comment]
I tried both methods... same issue... should I create a user variable or system environment variable?

**Comment by 3sv1n** [comment]
Hi the problem is fixed, but now i cant understand what the bot prefix is... do i set one myself? if so, how do i do that?

**Comment by Vinchethescript** [comment]
The prefix is `sb.`.

**Comment by Fleny113** [comment]
> Hi the problem is fixed, but now i cant understand what the bot prefix is... do i set one myself? if so, how do i do that?

If i remember correctly it is `sb.`

**Comment by 3sv1n** [comment]
hi thanks for the quick reply, so i hve typed sb.help and then this showed up in the terminal:
![err](https://user-images.githubusercontent.com/72260184/189473577-013967d9-369f-4a63-8bc1-f7ddba8abc71.JPG)

now how do i fix THIS?

**Comment by Vinchethescript** [comment]
Did you create a user with the permission to read and write to all databases? IIRC you should also allow all IPs to access the database, but I don't remember how at the moment.

**Comment by 3sv1n** [comment]
i didnt modify any user settings, instead i just followed the on-screen instructions to create and link a user, allow IP etc.
also, the user is set as atlasadmin, i guess i dont need to change that?

I will explore the part you mentioned and see if theres any updates

**Comment by 3sv1n** [comment]
1) I also set "allow from anywhere" in the list of allowed IPs, still the same
2) updated the roles of user, still same

**Comment by Vinchethescript** [comment]
The bot user's roles have nothing to do with this. Make sure you put the MongoDB connection string correctly, with the correct username and password.
