### ISSUE TITLE
Additional support for Music and Radio

### ISSUE THREAD

**Issue by delidolu1adam** [StrapBot/StrapBot#4]
The bot looks really nice, I will complete the Turkish and French translations and send them to you as soon as possible.

As you know, Discord bots no longer support youtube. Do you plan to add lines of code to support SoudCloud, Spotify and Custom URL for the bot?

You can also add an extra radio module for such a nice bot.

for example
!radio = lists the available radio list
!radio list = displays all available radio list
!radio example = starts playing the radio named "example" in the current radio list.
!radio add name url = Example: !radio add HipHop https://88.287.57.51:8080
!radio remove name = Example: !radio remove HipHop

Thank you very much. And have a nice day.y

**Comment by Vinchethescript** [comment]
At the moment, the bot is being rewritten from scratch, and with that I'll remove support for YouTube music. AFAIK, Spotify doesn't have official APIs for streaming, and I don't know if SoundCloud does.

I'm not maintaining the bot in this repository so I can continue rewriting it. The source code will be available when it'll be ready.

Thanks for your help and suggestions.
